# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"

  lane :github do |_options|
    create_keychain(
      name: 'ios_app_keychain',
      password: 'tpalzhffhs2020',
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )
    match(type: "appstore")
    build_app(workspace: 'DDYZD_V2.xcworkspace', scheme: 'DDYZD_V2')
    upload_to_app_store(
      force: true,
      reject_if_possible: true,
      skip_metadata: true,
      skip_screenshots: true,
      languages: ['ko'],
      release_notes: {
        'default' => 'bug fixed',
        'ko' => 'bug fixed'
      },
      submit_for_review: true,
      precheck_include_in_app_purchases: false,
      automatic_release: true,
      submission_information: {
        add_id_info_uses_idfa: true,
        add_id_info_serves_ads: true,
        add_id_info_tracks_install: true,
        add_id_info_tracks_action: false,
        add_id_info_limits_tracking: true,
        export_compliance_encryption_updated: false
      },
      api_key: api_key
    )
  end
end
