# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"

  lane :github do |_options|
    create_keychain(
      name: 'ios_app_keychain',
      password: ENV['MATCH_PASSWORD'],
      timeout: 3600,
      default_keychain: true,
      unlock: true,
      add_to_search_list: true,
    )
    match(type: "appstore", readonly: true, keychain_name: 'ios_app_keychain', keychain_password: ENV['MATCH_PASSWORD'])
    build_app(workspace: 'DDYZD_V2.xcworkspace', scheme: 'DDYZD_V2')
    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true,
      app_identifier: "com.semicolon.DDYZD-V2"
    )
  end
end
