# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDYZD_V2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDYZD_V2
  
  #Networking
  pod 'Alamofire', '~> 5.2'
  pod 'Socket.IO-Client-Swift', '~> 16.0.0'

  #Rx
  pod 'RxAlamofire', '~> 6.1'
  pod 'RxCocoa', '~> 6.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'RxSwift', '~> 6.0'

  #UI
  pod 'RxSkeleton', '~> 0.0.9'
  pod 'SkeletonView', '~> 1.15.0'
  pod 'SwiftOverlays', '~> 5.0.1'
  pod 'Tabman', '~> 2.9'
  pod 'ImageSlideshow', '~> 1.9.0'
  pod 'ImageSlideshow/Kingfisher', '~> 1.9.0'
  pod 'Kingfisher', '~> 6.0'

  #ect
  pod 'DSMSDK', '~> 1.3.0'
  pod 'KeychainSwift', '~> 19.0'
  pod 'Firebase/Messaging'
  pod 'Siren', '~> 5.8'
  
end
