# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDYZD_V2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDYZD_V2

  pod 'Alamofire', '~> 5.2'
  pod 'DSMSDK', '~> 1.1'
  pod 'Firebase/Messaging'
  pod 'RxAlamofire', '~> 6.1'
  pod 'RxCocoa', '~> 6.0'
  pod 'RxSwift', '~> 6.0'
  
end
