# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDYZD_V2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDYZD_V2

  pod 'Alamofire', '~> 5.2'
  pod 'DSMSDK', '~> 1.1.1'
  pod 'Firebase/Messaging'
  pod 'ImageSlideshow', '~> 1.9.0'
  pod 'ImageSlideshow/Kingfisher', '~> 1.9.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'RxAlamofire', '~> 6.1'
  pod 'RxCocoa', '~> 6.0'
  pod 'RxSwift', '~> 6.0'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'Tabman', '~> 2.9'
  
end
